# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashBoard(object):
    def setupUi(self, DashBoard):
        DashBoard.setObjectName("DashBoard")
        DashBoard.resize(1024, 700)
        DashBoard.setStyleSheet("*{\n"
"    font: 12pt \"맑은 고딕\";\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: white;\n"
"}\n"
"#label_title_1,\n"
"#label_title_2{\n"
"    font: bold 20pt \"맑은 고딕\";\n"
"}\n"
"\n"
"#label_ordinary_count,\n"
"#label_heavy_count{\n"
"    font: 32pt \"맑은 고딕\";\n"
"}\n"
"\n"
"#label_category_1,\n"
"#label_category_2{\n"
"    font: bold 16pt;\n"
"}\n"
"\n"
"\n"
"#circle_widget,\n"
"#circle_widget_2\n"
"{\n"
"    background-image: url(:/newPrefix/circle.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"QSlider{\n"
"    height: 80px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal{\n"
"    height: 80px;\n"
"    margin: 40px 40px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    image: url(:/newPrefix/upper_arrow.png);\n"
"    border: none;\n"
"    margin: -20px 0;\n"
"    border-radius: 20px;\n"
"    padding: -20px 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(DashBoard)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setMaximumSize(QtCore.QSize(450, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title_1 = QtWidgets.QLabel(self.widget_4)
        self.label_title_1.setObjectName("label_title_1")
        self.verticalLayout.addWidget(self.label_title_1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.widget_4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_3 = QtWidgets.QFrame(self.widget_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_title_2 = QtWidgets.QLabel(self.widget_5)
        self.label_title_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_title_2.setObjectName("label_title_2")
        self.verticalLayout_3.addWidget(self.label_title_2)
        self.label_gradient = QtWidgets.QLabel(self.widget_5)
        self.label_gradient.setMinimumSize(QtCore.QSize(0, 50))
        self.label_gradient.setMaximumSize(QtCore.QSize(550, 50))
        self.label_gradient.setText("")
        self.label_gradient.setPixmap(QtGui.QPixmap(":/newPrefix/spectrum.png"))
        self.label_gradient.setScaledContents(True)
        self.label_gradient.setObjectName("label_gradient")
        self.verticalLayout_3.addWidget(self.label_gradient)
        self.horizontalSlider = QtWidgets.QSlider(self.widget_5)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_3.addWidget(self.horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_6)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.circle_widget = QtWidgets.QWidget(self.widget_2)
        self.circle_widget.setMinimumSize(QtCore.QSize(200, 250))
        self.circle_widget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.circle_widget.setObjectName("circle_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.circle_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ordinary_count = QtWidgets.QLabel(self.circle_widget)
        self.label_ordinary_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ordinary_count.setObjectName("label_ordinary_count")
        self.horizontalLayout_3.addWidget(self.label_ordinary_count)
        self.verticalLayout_5.addWidget(self.circle_widget)
        self.label_category_1 = QtWidgets.QLabel(self.widget_2)
        self.label_category_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_category_1.setObjectName("label_category_1")
        self.verticalLayout_5.addWidget(self.label_category_1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_6)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.circle_widget_2 = QtWidgets.QWidget(self.widget_3)
        self.circle_widget_2.setMinimumSize(QtCore.QSize(0, 250))
        self.circle_widget_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.circle_widget_2.setObjectName("circle_widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.circle_widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_heavy_count = QtWidgets.QLabel(self.circle_widget_2)
        self.label_heavy_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heavy_count.setObjectName("label_heavy_count")
        self.horizontalLayout_4.addWidget(self.label_heavy_count)
        self.verticalLayout_4.addWidget(self.circle_widget_2)
        self.label_category_2 = QtWidgets.QLabel(self.widget_3)
        self.label_category_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_category_2.setObjectName("label_category_2")
        self.verticalLayout_4.addWidget(self.label_category_2)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout.addWidget(self.widget)
        DashBoard.setCentralWidget(self.centralwidget)

        self.retranslateUi(DashBoard)
        QtCore.QMetaObject.connectSlotsByName(DashBoard)

    def retranslateUi(self, DashBoard):
        _translate = QtCore.QCoreApplication.translate
        DashBoard.setWindowTitle(_translate("DashBoard", "응급실_대시보드"))
        self.label_title_1.setText(_translate("DashBoard", "응급환자 진료상황"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DashBoard", "번호"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DashBoard", "환자(나이)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DashBoard", "담당의/간호사"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DashBoard", "진행상황"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("DashBoard", "IC-1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("DashBoard", "김철수(M/55)"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("DashBoard", "김순재/조운"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("DashBoard", "접수중"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_title_2.setText(_translate("DashBoard", "응급실 혼잡도"))
        self.label_ordinary_count.setText(_translate("DashBoard", "8\n"
"명"))
        self.label_category_1.setText(_translate("DashBoard", "일반환자"))
        self.label_heavy_count.setText(_translate("DashBoard", "3\n"
"명"))
        self.label_category_2.setText(_translate("DashBoard", "중증환자"))
from Client.ui import my_qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashBoard = QtWidgets.QMainWindow()
    ui = Ui_DashBoard()
    ui.setupUi(DashBoard)
    DashBoard.show()
    sys.exit(app.exec_())
